---
sidebar: sidebar 
permalink: ontap-security-hardening/data-replication-encryption.html 
keywords: tr-4569, ontap hardening guide, encrypted SnapMirror, SnapVault, FlexCache, pre-shared key, TLS 1.2, TLS 1.3, TLS 
summary: 使用資料複製加密，透過 ONTAP 叢集之間的預先共用金鑰，對 SnapMirror、SnapVault、FlexCache 的複寫流量進行 TLS 加密。 
---
= 資料複寫加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了補充靜態資料加密，您可以使用 TLS 和預共用金鑰對叢集之間的 ONTAP 資料複製流量進行加密，金鑰可以是 SnapMirror、SnapVault 或 FlexCache。

當複寫資料以進行災難恢復、快取或備份時、您必須在從ONTAP 一個叢集傳輸到另一個叢集的過程中、透過線路來保護資料。這樣做可防止惡意攔截式攻擊、攻擊正在傳輸的敏感資料。

從 ONTAP 9.6 開始，叢集對等加密為 ONTAP 資料複製功能（例如 SnapMirror、SnapVault 和 FlexCache）提供 TLS 1.2 AES-256 GCM 加密支援。加密是透過兩個叢集對等體之間的預共用金鑰（PSK）來設定的。

從 ONTAP 9.15.1 開始，叢集對等加密為 ONTAP 資料複製功能（例如 SnapMirror、SnapVault 和 FlexCache）提供 TLS 1.3 AES-256 GCM 加密支援。加密是透過兩個叢集對等體之間的預共用金鑰（PSK）來設定的。

使用 NSE、NVE 和 NAE 等技術保護靜態資料的客戶，也可以透過升級到 ONTAP 9.6 或更高版本來使用叢集對等加密，從而實現端對端資料加密。

叢集對等連線會對叢集對等節點之間的所有資料進行加密。例如，使用 SnapMirror 時，所有對等連線資訊以及來源叢集對等節點和目標叢集對等節點之間的所有 SnapMirror 關係都會被加密。啟用叢集對等連線加密後，您無法在叢集對等節點之間傳送明文資料。

從 ONTAP 9.6 開始，新建立的叢集對等關係預設會啟用加密。若要在 ONTAP 9.6 之前建立的叢集對等關係上啟用加密，您必須將來源叢集和目的地叢集升級至 9.6。此外，您還必須使用  `cluster peer modify` 命令將來源叢集對等端點和目的地叢集對等端點都變更為使用叢集對等加密。

您可以按照以下範例所示、將現有的對等關係轉換為在 ONTAP 9.6 中使用叢集對等加密：

[listing]
----
On the destination cluster peer:

cluster2::> cluster peer modify cluster1 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter a passphrase.

On the source cluster peer:

cluster1::> cluster peer modify cluster2 -auth-status-admin use-authentication -encryption-protocol-proposed tls-psk

When prompted enter the same passphrase you created in the previous step.
----