---
sidebar: sidebar 
keywords: Databases, Applications, Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: apps-dbs.html 
summary: 這些技術報告概述 ONTAP 上的應用程式和資料庫、以及建議的實務做法 
---
= 應用程式與資料庫技術報告
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP 是許多企業應用程式與資料庫技術的資料管理與資料保護基礎。下列技術報告提供 NetApp 針對 Microsoft SQL Server 、 MySQL 、 Oracle 、 PostgreSQL 和 SAP HANA 所建議的實務做法和實作程序指引。



== Microsoft SQL Server

SQL Server 是 Microsoft 資料平台的基礎、無論是在內部部署或雲端、都能以記憶體內建技術提供關鍵任務效能、並更快洞悉任何資料。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mssql/mssql-overview.html["Microsoft SQL Server with ONTAP 的最佳實務做法"]
瞭解儲存管理員和資料庫管理員如何在 ONTAP 儲存設備上成功部署 Microsoft SQL Server 。


NOTE: 本文件取代先前發佈的技術報告 _TR-4590 ： Microsoft SQL Server 與 ONTAP 的最佳實務做法指南。 _

link:https://www.netapp.com/pdf.html?item=/media/88704-tr-4976-virtualized-microsoft-sql-server-performance-on-netapp-aff-a-series-and-c-series.pdf["TR-4976 ： NetApp AFF A 系列和 C 系列系統上的虛擬化 Microsoft SQL Server 效能"^]
瞭解使用 NetApp AFF A 系列和 C 系列系統的 Microsoft SQL Server 效能特性、以及如何根據工作負載選擇正確系統的指引。

link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714 ：使用 SnapCenter 的 Microsoft SQL Server 最佳實務做法"^]
立即瞭解如何使用 SnapCenter 技術在 ONTAP 儲存設備上成功部署 Microsoft SQL Server 、以保護資料。



== MySQL

本文檔介紹了配置要求，並提供了有關在 ONTAP 上部署 MySQL 的調整和存儲配置的指導。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/mysql/mysql-overview.html["NetApp ONTAP 最佳實務做法的 MySQL 資料庫"]
MySQL 及其變種（包括 MariaDB 和 Percona ）廣泛用於許多企業應用程式。這些應用程式涵蓋全球社群網站和大量的經濟應用系統、以及包含數千個資料庫執行個體的中小企業代管系統。瞭解在 ONTAP 上部署 MySQL 的組態需求、以及調整與儲存組態的相關指引。


NOTE: 本文件取代先前發佈的技術報告 _TR-4722 ： NetApp ONTAP 最佳實務做法的 MySQL 資料庫。 _



== Oracle

ONTAP 專為 Oracle 資料庫所設計。數十年來、 ONTAP 已針對關聯式資料庫 I/O 的獨特需求進行最佳化、並特別建立多項 ONTAP 功能、以滿足 Oracle 資料庫的需求、甚至是 Oracle Inc. 本身的要求。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["ONTAP 上的 Oracle 資料庫"]
瞭解可讓儲存管理員和資料庫管理員在 ONTAP 儲存設備上成功部署 Oracle 的建議實務做法。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-dp-introduction.html["使用 ONTAP 保護 Oracle 資料"]
瞭解可讓儲存管理員和資料庫管理員在 ONTAP 儲存設備上成功備份、恢復、複寫及提供災難恢復給 Oracle 的建議實務做法。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-dr-overview.html["使用 ONTAP 進行 Oracle 災難恢復"]
瞭解在 MetroCluster 和 SnapMirror 業務連續性上操作 Oracle 資料庫的建議實務做法、測試程序及其他考量事項。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["將 Oracle 資料庫移轉至 ONTAP 儲存系統"]
瞭解規劃移轉策略的整體考量、進行資料移動的三個不同層級、並詳細說明一些可用的各種程序。


NOTE: 以上連結的文件取代了先前發佈的技術報告 _TR-3633 ： ONTAP 上的 Oracle 資料庫； TR-4591 ： Oracle 資料保護：備份、還原、複寫； TR-4592 ： MetroCluster 上的 Oracle ；以及 TR-4534 ：將 Oracle 資料庫移轉至 NetApp 儲存系統

link:https://www.netapp.com/pdf.html?item=/media/85630-tr-4969.pdf["TR-4969 ： AFF A 系列和 C 系列上的 Oracle 資料庫效能"^]
ONTAP 是功能強大的資料管理平台、具備內嵌壓縮、不中斷硬體升級、以及從外部儲存陣列匯入 LUN 的原生功能。最多可將 24 個節點叢集在一起、同時透過網路檔案系統（ NFS ）、伺服器訊息區（ SMB ）、 iSCSI 、光纖通道（ FC ）和非揮發性記憶體高速（ NVMe ）傳輸協定來提供資料。此外、 Snapshot 技術是建立數萬個線上備份和完整運作資料庫複本的基礎。除了豐富的 ONTAP 功能集之外、還有各式各樣的使用者需求、包括資料庫大小、效能需求和資料保護需求。瞭解使用 AFF 儲存系統（包括 A 系列和 C 系列）的裸機資料庫效能、其中涵蓋兩種 AFF 選項之間的最大值和實際差異。

link:https://www.netapp.com/pdf.html?item=/media/85629-tr-4971.pdf["TR-4971 ： AFF A 系列和 C 系列上的虛擬化 Oracle 資料庫效能"^]
ONTAP 是功能強大的資料管理平台、具備內嵌壓縮、不中斷硬體升級、以及從外部儲存陣列匯入 LUN 的原生功能。最多可將 24 個節點叢集在一起、同時透過網路檔案系統（ NFS ）、伺服器訊息區（ SMB ）、 iSCSI 、光纖通道（ FC ）和非揮發性記憶體高速（ NVMe ）傳輸協定來提供資料。此外、 Snapshot 技術是建立數萬個線上備份和完整運作資料庫複本的基礎。除了豐富的 ONTAP 功能集之外、還有各式各樣的使用者需求、包括資料庫大小、效能需求和資料保護需求。瞭解使用 AFF 儲存系統（包括 A 系列和 C 系列）的虛擬化資料庫效能、其中涵蓋兩種 AFF 選項之間的最大值和實際差異。

link:https://www.netapp.com/pdf.html?item=/media/9138-tr4695.pdf["TR-4695 ：使用 FabricPool 進行資料庫儲存分層"^]
瞭解 FabricPool 的優點和組態選項、包括 Oracle 關聯式資料庫管理系統（ RDBMS ）。

link:https://www.netapp.com/pdf.html?item=/media/40384-tr-4899.pdf["TR-4899 ： Oracle 資料庫透明化應用程式容錯移轉、採用 SnapMirror Business Continuity"^]
SnapMirror Business Continuity （ SM-BC ）和 Oracle Real Application Cluster （ RAC ）可在發生站台中斷和真正災難時、提供透明的應用程式容錯移轉（ TAF ）和持續性。瞭解 AFF 儲存陣列的組態指南和建議實務做法、並將 SMBC 作為 Oracle RAC 的儲存元件。

link:https://www.netapp.com/pdf.html?item=/media/21901-tr-4876.pdf["TR-4876 ：採用 ONTAP 解決方案和部署最佳實務做法的 Oracle 多租戶"^]
瞭解解決方案建議的實務做法、瞭解如何使用 ONTAP 儲存設備來配置、管理及保護 Oracle 多租戶資料庫、以充分發揮 Oracle 多租戶資料庫的效益、以及 ONTAP 軟體的功能。



== PostgreSQL

PostgreSQL 隨附的變種包括 PostgreSQL 、 PostgreSQL Plus 和 EDBS PostgreSQL 進階伺服器（ EPAS ）。PostgreSQL 通常部署為多層應用程式的後端資料庫。NetApp ONTAP 是執行 PostgreSQL 資料庫的絕佳選擇、可確保其可靠性、高效能及高效率的資料管理功能。

link:https://docs.netapp.com/us-en/ontap-apps-dbs/postgres/postgres-overview.html["ONTAP 最佳實務做法的 PostgreSQL 資料庫"]
PostgreSQL 隨附的變種包括 PostgreSQL 、 PostgreSQL Plus 和 EDBS PostgreSQL 進階伺服器（ EPAS ）。PostgreSQL 通常部署為多層應用程式的後端資料庫。它受一般中介軟體套件的支援（例如 PHP 、 Java 、 Python 、 Tcl/Tk 、 ODBC 、 和 JDBC) ，過去一直是開放原始碼資料庫管理系統的熱門選擇。瞭解在 ONTAP 上部署 PostgreSQL 的組態需求、以及調整與儲存組態的相關指引。


NOTE: 本文件取代先前發佈的技術報告 TR-4770 ： ONTAP 最佳實務實務的 PostgreSQL 資料庫。



== SAP HANA

設定、管理及自動化 SAP 解決方案的最佳實務做法、請參閱 NetApp SAP 解決方案頁面。

link:https://docs.netapp.com/us-en/netapp-solutions-sap/["ONTAP 上的 SAP HANA 資料庫解決方案"]
