---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: 自動化功能可讓組織將 Zero Trust 部署規模擴充至手動程序之外、以抵禦同樣自動化的誤報活動 
---
= ONTAP 外部的 NetApp 安全性自動化與協調控制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自動化功能可讓您以最少的人力協助來執行程序或程序。自動化功能可讓組織將 Zero Trust 部署規模擴充至遠超出手動程序的範圍、以抵禦同樣自動化的誤報活動。

Ansible 是開放原始碼軟體資源配置、組態管理及應用程式部署工具。它可以在許多類似 Unix 的系統上執行、而且可以同時設定類似 Unix 的系統和 Microsoft Windows 。其中包含自己的宣告語言、可用來描述系統組態。Ansible 由 Michael DeHaan 撰寫、並於 2015 年由 Red Hat 收購。Ansible 是無代理程式、可透過 SSH 或 Windows 遠端管理（允許遠端執行 PowerShell ）進行遠端連線以執行工作。NetApp 開發的不只是、還 https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 個適用於 ONTAP 軟體的 Ansible 模組"^]能進一步整合 Ansible 自動化架構。適用於 NetApp 的 Ansible 模組提供一組指示、說明如何定義所需的狀態、並將其轉送至目標 NetApp 環境。模組的設計可支援設定授權、建立集合體和儲存虛擬機器、建立磁碟區、以及還原快照等工作。Ansible 角色 https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["發表於 GitHub"^] 專屬於 NetApp DoD 統一化功能（ UC ）部署指南。

使用者可以利用可用模組庫輕鬆開發 Ansible 教戰手冊，並根據自己的應用程式和業務需求自訂這些手冊，以自動化日常工作。在撰寫教戰手冊之後、您可以執行該手冊來執行指定的工作、這樣可以節省時間並提高生產力。NetApp 已建立並共用範例教戰手冊、可直接使用或根據您的需求自訂。

Data Infrastructure Insights是一種基礎設施監控工具，可讓您了解完整的基礎架構。透過Data Infrastructure Insights，您可以監控、排除故障並最佳化所有資源，包括公有雲實例和私有資料中心。Data Infrastructure Insights可以將平均解決時間縮短 90%，並防止 80% 的雲端問題影響最終用戶。它還可以平均降低 33% 的雲端基礎設施成本，並透過使用可操作的情報來保護您的資料來減少您受到內部威脅的風險。Data Infrastructure Insights的儲存工作負載安全功能支援透過 AI 和 ML 進行使用者行為分析，以便在因內部威脅而出現異常使用者行為時發出警報。對於ONTAP，儲存工作負載安全使用零信任 FPolicy 引擎。
